Update terraform.yml
Capture the exitcode of "[Terraform] Plan" to be re-used in the apply step validation without stop the pipeline.

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -160,6 +160,18 @@ jobs:
             -var="project_name=${{ secrets.TF_PROJECT_NAME }}" \
             -var="db_user=${{ secrets.TF_DB_USER }}" \
             -var="db_pass=${{ secrets.TF_DB_PASS }}"
+          exit_code=$?
+      
+          if [ $exit_code -eq 1 ]; then
+            echo "Terraform plan failed."
+            exit 1
+          elif [ $exit_code -eq 0 ]; then
+            echo "No changes detected."
+          elif [ $exit_code -eq 2 ]; then
+            echo "Changes detected in plan."
+          fi
+      
+          echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
